variable "vmanage_image" {}
variable "viptela_instances_type" {}
variable "region" {}
variable "Vipela_Control_Plane" {}
variable "counter" {}
variable "subnet" {}
variable "resource_group_name" {}
variable "username" {}
variable "password" {}
variable "avsetvmanage" {}
variable "vbond" {}
variable "org_name" {}
variable "sp_org_name" {}
